
name: app_any_rss_wf

on:
  schedule:
    - cron: '0 13 * * *'  # This example runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'  # Specify Python version, e.g., '3.8'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run the Python script
        run: python3 app_any_rss_reader.py  # Replace with the name of your Python script

      - name: Create output directory
        run: |
          mkdir -p feeds
          mkdir -p feeds/rss_feeds/

      - name: Move generated XML file
        run: mv app_any_feed.xml feeds/rss_feeds/

      - name: Commit and push XML file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add feeds/rss_feeds/app_any_feed.xml
          git commit -m "Update RSS feed XML file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN_PUB }}
